[tools]
node = "25.9.0"
uv = "0.11.16"

[tasks.sync]
run = "uv sync --dev --frozen && uv run pre-commit install"

[tasks.pack]
run = [
  "uv run python scripts/generate_build_info.py",
  "uv run pyinstaller yt-downloader.spec",
]

[tasks.run]
run = "uv run yt-downloader"

[tasks.pre-commit]
run = "uv run pre-commit run --show-diff-on-failure --color=always --all-files"

[tasks.check]
run = ["mise run pre-commit", "mise run pack"]
