from __future__ import annotations

import datetime
import subprocess
import sys
from importlib.metadata import PackageNotFoundError, version
from pathlib import Path


def _git(*args: str) -> str:
    """Run a git command; return stripped stdout, or empty string on any failure."""
    try:
        result = subprocess.run(
            ["git", *args],
            capture_output=True,
            text=True,
            timeout=3,
            cwd=Path(__file__).parent,
        )
        return result.stdout.strip() if result.returncode == 0 else ""
    except Exception:
        return ""


def _get_package_version() -> str:
    if getattr(sys, "frozen", False):
        try:
            import importlib

            _bi = importlib.import_module("yt_downloader._build_info")
            return str(getattr(_bi, "BUILD_VERSION", "unknown"))
        except ImportError:
            return "unknown"
    try:
        return version("yt-downloader")
    except PackageNotFoundError:
        return "unknown"


def _get_build_info() -> tuple[str, str, str, str, bool]:
    """Return (commit, ref, commit_date, build_time, dirty).

    ref is the branch name, or the tag name when on a tag / detached HEAD.
    When running as a frozen PyInstaller executable, values come from the
    embedded _build_info module generated by scripts/generate_build_info.py.
    """
    if getattr(sys, "frozen", False):
        try:
            import importlib

            _bi = importlib.import_module("yt_downloader._build_info")
            return (
                str(getattr(_bi, "BUILD_COMMIT", "unknown")),
                str(getattr(_bi, "BUILD_BRANCH", "unknown")),
                str(getattr(_bi, "BUILD_COMMIT_DATE", "unknown")),
                str(getattr(_bi, "BUILD_TIME", "unknown")),
                bool(getattr(_bi, "BUILD_DIRTY", False)),
            )
        except ImportError:
            return "unknown", "unknown", "unknown", "unknown", False

    commit = _git("rev-parse", "--short", "HEAD")
    ref = _git("rev-parse", "--abbrev-ref", "HEAD")
    if ref == "HEAD":
        # Detached HEAD — try to resolve an exact tag
        ref = _git("describe", "--tags", "--exact-match") or "HEAD"
    commit_date = _git("log", "-1", "--format=%cI")
    porcelain = _git("status", "--porcelain")
    dirty = porcelain != ""
    build_time = datetime.datetime.now(datetime.UTC).strftime("%Y-%m-%dT%H:%M:%SZ")
    return (
        commit or "unknown",
        ref or "unknown",
        commit_date or "unknown",
        build_time,
        dirty,
    )


__version__: str = _get_package_version()
__commit__: str
__ref__: str
__commit_date__: str
__build_time__: str
__dirty__: bool
__commit__, __ref__, __commit_date__, __build_time__, __dirty__ = _get_build_info()


def format_version_info() -> str:
    """Return a formatted multi-line version string."""
    dirty_mark = "-dirty" if __dirty__ else ""
    return (
        f"yt-downloader {__version__}{dirty_mark}\n"
        f"  commit     : {__commit__}\n"
        f"  ref        : {__ref__}\n"
        f"  commit time: {__commit_date__}\n"
        f"  build time : {__build_time__}"
    )
