#!/usr/bin/env python3
"""Generate src/yt_downloader/_build_info.py with current git metadata.

Run this before `pyinstaller` so the frozen binary embeds the correct build info.
Usage: uv run python scripts/generate_build_info.py
"""

from __future__ import annotations

import datetime
import subprocess
import sys
from importlib.metadata import PackageNotFoundError, version
from pathlib import Path


def git(*args: str) -> str:
    """Run a git command and return stripped stdout, or 'unknown' on failure."""
    try:
        result = subprocess.run(
            ["git", *args],
            capture_output=True,
            text=True,
            timeout=10,
            cwd=Path(__file__).parent.parent,
        )
        return result.stdout.strip() if result.returncode == 0 else "unknown"
    except Exception:
        return "unknown"


def main() -> None:
    out = Path(__file__).parent.parent / "src" / "yt_downloader" / "_build_info.py"

    commit = git("rev-parse", "--short", "HEAD")
    ref = git("rev-parse", "--abbrev-ref", "HEAD")
    if ref == "HEAD":
        tag = git("describe", "--tags", "--exact-match")
        ref = tag if tag != "unknown" else "HEAD"
    commit_date = git("log", "-1", "--format=%cI")
    porcelain = git("status", "--porcelain")
    dirty = porcelain not in ("unknown", "")
    build_time = datetime.datetime.now(datetime.UTC).strftime("%Y-%m-%dT%H:%M:%SZ")

    try:
        pkg_version = version("yt-downloader")
    except PackageNotFoundError:
        pkg_version = "unknown"

    lines = [
        "# Auto-generated by scripts/generate_build_info.py — do not edit manually\n",
        f'BUILD_VERSION = "{pkg_version}"\n',
        f'BUILD_COMMIT = "{commit}"\n',
        f'BUILD_BRANCH = "{ref}"\n',
        f'BUILD_COMMIT_DATE = "{commit_date}"\n',
        f'BUILD_TIME = "{build_time}"\n',
        f"BUILD_DIRTY = {dirty}\n",
    ]
    out.write_text("".join(lines), encoding="utf-8")
    print(f"Generated {out}", file=sys.stderr)
    print(f"  version : {pkg_version}", file=sys.stderr)
    print(f"  commit  : {commit}", file=sys.stderr)
    print(f"  ref     : {ref}", file=sys.stderr)
    print(f"  date    : {commit_date}", file=sys.stderr)
    print(f"  time    : {build_time}", file=sys.stderr)
    print(f"  dirty   : {dirty}", file=sys.stderr)


if __name__ == "__main__":
    main()
