name: PR Check

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up mise
        uses: jdx/mise-action@v2

      - name: Sync environment
        run: mise run sync

      - name: Check all
        run: mise run check
